---
title: "Capítulo 1"
author: "André Solér Kalinovski"
output: 
  html_document:
    toc: true
    toc_depth: 2
---

# Capítulo 1

## Exercícios Recomendados

Segue a resolução dos exercícios 3, 10, 14, 21, 29, 33, 38, 43, 44, 47, 48.  

**3** A coin is to be tossed until a head appears twice in a row. What is the sample space for this experiment? If the coin is fair, what is the probability that it will be tossed exactly four times?  

| 
|   
|     Sejam $H$ e $T$, respectivamente, os resultados cara e cora do lançamento.  
|     $\Omega = \{(H,H),(T,H,H),(H,T,H,H),(T,T,H,H),(H,T,T,H,H),(T,H,T,H,H),(T,T,T,H,H),...\}$  
|     Seja $X$ o número de lançamentos da moeda até que acabe o experimento.  
|     $P(X=4) = P(H,T,H,H) + P(T,T,H,H) = \frac1{16} +\frac1{16} = \frac18$.  
|       
|       
|       

**10**  Show that $P\Bigl(\bigcup_{i=1}^{n}E_i\Bigr)\leq\sum_{i=1}^{n}P(E_i)$. This is known as Boole’s inequality.  

| 
|   
|     Hipótese de indução: $P\Bigl(\bigcup_{i=1}^{n}E_i\Bigr)\leq\sum_{i=1}^{n}P(E_i)$.  
|     Caso base: $n = 2$:  
|     $P(E_1 \cup E_2) = P(E_1) + P(E_2) - P(E_1 \cap E_2) = \sum_{i=1}^{2}P(E_i) - P(E_1 \cap E_2) \leq \sum_{i=1}^{2}P(E_1)$.  
|     Assuma que a afirmação $P\Bigl(\bigcup_{i=1}^{n}E_i\Bigr)\leq\sum_{i=1}^{n}P(E_i)$ é válida para $n=k$. Se é válida para $n=k$, também o é para $n = k+1$:  
|     $P\Bigl(\bigcup_{i=1}^{k+1}E_i\Bigr)=P\Bigl(\bigcup_{i=1}^{k}\cup E_{k+1}\Bigr)= P\Bigl(\bigcup_{i=1}^{k}\Bigr)+P(E_{k+1}) - P\Bigl(\bigcup_{i=1}^{k}\cap E_{k+1}\Bigr) \leq \sum_{i=1}^kP(E_i) + P(E_{k+1}) - P\Bigl(\bigcup_{i=1}^{k}\cap E_{k+1}\Bigr)$  
|     $=\sum_{i=1}^{k+1}P(E_i) - P\Bigl(\bigcup_{i=1}^{k}\cap E_{k+1}\Bigr) \leq \sum_{i=1}^{k+1}P(E_i)$   
|     Logo, pelo caso caso base, hipótese de indução e o passo indutivo temos que a afirmação  
|     $P\Bigl(\bigcup_{i=1}^{n}E_i\Bigr)\leq\sum_{i=1}^{n}P(E_i)$  é válida para todo $\{n \in \mathbb{N}:n\ge 2\}$.  
|   
|   
|   

**14** The probability of winning on a single toss of the dice is p. A starts, and if he fails, he passes the dice to B, who then attempts to win on her toss. They continue tossing the dice back and forth until one of them wins. What are their respective probabilities of winning?  

| 
|   
|     Seja $0$ a falha no lançamento dos dados e $1$ o sucesso. $A$ vence se ocorrer:  
|     $\{(1),(0,0,1),(0,0,0,0,1),...\}$, ou seja, temos um sucesso e um número par de fracassos. Sendo $X$ o vencedor, temos:
|     $P(X=A) = p \cdot\sum_{i=0}^\infty(1-p)^{2i}= p \cdot \sum_{i=0}^\infty \bigl((1-p)^2\bigr)^i$ = $p\cdot \frac{1}{1-(1-p)^2} = \frac{p}{1-(1-2p+p^2)} = \frac{p}{2p-p^2} = \frac{p}{p(2-p)}=\frac1{2-p}$.  
|     $P(X=B) = 1 - P(X=B^c) = 1 - P(X=A) = \frac{2-p}{2-p} - \frac{1}{2-p} = \frac{1-p}{2-p}$.  
|   
|   
|   

**21** Suppose that 5 percent of men and 0.25 percent of women are color-blind. A colorblind person is chosen at random. What is the probability of this person being male? Assume that there are an equal number of males and females.  

| 
|   
|     Seja $M$ o evento ser homem. Seja $D$ o evento ser daltônico.  
|     $P(M|D)=\frac{P(D|M)\cdot P(M)}{P(D)} =  \frac{0,05\cdot1/2}{1/2\cdot0,0025+1/2\cdot0,05} = \frac{0,05}{0,0025+0,05}= \frac{500}{525}=\frac{20}{21}$.  
|   
|   
|   

**29**  Suppose that $P(E) = 0.6$. What can you say about $P(E|F)$ when  

**a)** $E$ and $F$ are mutually exclusive?  

| 
|     $P(E|F)=\frac{P(E \cap F)}{P(F)}=0$.  
|   
|   

**b)** $E \subset F$?  

| 
|     $P(E|F) = \frac{P(E\cap F)}{P(F)}=\frac{P(E)}{P(F)}=\frac{0,6}{P(F)}$.  
|   
|   

**c)** $F \subset E$?  

| 
|     $P(E|F)= \frac{P(E\cap F)}{P(F)} = \frac{P(F)}{P(F)}=1$.  
|   
|   
|   

**33** In a class there are four freshman boys, six freshman girls, and six sophomore boys. How many sophomore girls must be present if sex and class are to be independent when a student is selected at random?  

| 
|   
|     Nota: ao invés de estudante de segundo ano, considerei *sophomore* veterano por ser mais conveniente de escrever.
|  
|     Para que as variáveis sexo e classe sejam dependentes, a proporção de garotas deve ser a mesma nas duas classes. Logo temos:  
|         $\frac{Número \; de \; Veteranas}{6} = \frac64 \Rightarrow Número \; de \; Veteranas = \frac{36}4=9$  
|   
|   
|   

**38** Urn 1 contains two white balls and one black ball, while urn 2 contains one white ball and five black balls. One ball is drawn at random from urn 1 and placed in urn 2. A ball is then drawn from urn 2. It happens to be white. What is the probability that the transferred ball was white?

| 
|  
|     Sejam $X_1$ e $X_2$, respectivamente, as cores das bolas retiradas das urnas 1 e 2. Seja $B$ o evento retirada de bola branca.   
|     $P(X_1=B|X_2=B) = \frac{P(X_2=B|X_1=B)P(X_1=B)}{P(X_2=B)} = \frac{2/7\cdot2/3}{2/3\cdot2/7+1/3\cdot1/7} = \frac{4/21}{4/21+1/21}=\frac{4}{5}$.  
|   
|   
|   

**43**  Suppose we have ten coins which are such that if the ith one is flipped then heads will appear with probability i/10, i = 1, 2, ... , 10. When one of the coins is randomly selected and flipped, it shows heads. What is the conditional probability that it was the fifth coin?  

| 
|   
|     Seja $X$ o resultado do lançamento da moeda. Seja $H$ a ocorrência do evento cara.  
|     $P(i=5|X=H)= \frac{P(i=5\cap X=H)}{P(X=H)} = \frac{1/10\cdot5/10}{1/10\sum_{i=1}^{10}\frac{i}{10}}$ = $\frac{5/10}{(\frac{1}{10}+\frac{10}{10})/2\cdot10} = \frac{1/2}{11/2}=\frac1{11}$ . 
|   
|   
|   

**44** Urn 1 has five white and seven black balls. Urn 2 has three white and twelve black balls. We flip a fair coin. If the outcome is heads, then a ball from urn 1 is selected, while if the outcome is tails, then a ball from urn 2 is selected. Suppose that a white ball is selected. What is the probability that the coin landed tails?  

| 
|   
|     Sejam os eventos $T$ a ocorrência de coroa no lançamento da moeda e $B$ a retirada de uma bola branca. Seja $X$ o resultado da urna e $Y$ o  
|     resultado do lançamento da moeda.  
|     $P(Y=T|X=B) = \frac{P(X=B|Y=T)\cdot P(Y=T)}{P(X=B)} = \frac{3/15\cdot1/2}{1/2\cdot5/12+1/2\cdot3/15} = \frac{3/15}{5/12+3/15}=\frac{12/60}{(25+12)/60}=\frac{12}{37}$.  
|   
|   
|   

**47** For a fixed event $B$, show that the collection $P(A|B)$, defined for all events $A$, satisfies the three conditions for a probability. Conclude from this that $P(A|B) = P(A|BC)P(C|B) + P(A|BC^c)P(C^c|B)$. Then directly verify the preceding equation.

| 
|   
|     ***i*** $P(A|B) = \frac{P(A\cap B)}{P(B)} \le \frac{P(B)}{P(B)} = 1 \Rightarrow P(A|B)\le1$.  
|     $P(A|B) = \frac{P(A\cap B)}{P(B)} \ge P(A\cap B) = P(A|B)P(B) \Rightarrow P(A|B) \ge P(A|B)P(B)$. Como $1\ge P(B)\ge0$, temos que $P(A|B)\ge0$.  
|     ***ii*** $P(A|B) + P(A^c|B) = P(A^c\cup A|B)= 1$.  
|     ***iii*** Sejam $A_1$ e $A_2$ eventos contidos em $A$ e sejam $A_1$ e $A_2$ disjuntos.  
|     $P\bigl((A_1\cup A_2)|B\bigr)=P(A_1|B)+P\bigl(A_2|B)-P\bigl((A_1\cap A_2)|B)\bigr)=P(A_1|B)+P(A_2|B)$.  
|   
|     $P(A|BC)P(C|B) +P(A|BC^c)P(C^c|B)= \frac{P(A|BC)P(B\cap C)+P(A|BC^c)P(C^c\cap B)}{P(B)} = \frac{P(A \cap B \cap C)+P(A \cap B \cap C^c)}{P(B)}=\frac{P(A \cap B)}{P(B)} = P(A|B)$.  
|   
|   
|   

**48** Sixty percent of the families in a certain community own their own car, thirty percent own their own home, and twenty percent own both their own car and their own home. If a family is randomly chosen, what is the probability that this family owns a car or a house but not both?

| 
|   
|     Seja $A$ o evento possuir um carro. Seja $B$ o evento possuir uma casa.
|     Podemos expressar a ocorrência de apenas $A$ ou apenas $B$ por $P(A\cap B^c) + P(B\cap A^c)$  
|     = $P(A \cup B) - P(A\cap B) - P(B \cap A^c) + P(B \cap A^c)=P(A\cup B) - P(A\cap B) =$  
|     $P(A) + P(B) - P(A\cap B) - P(A\cap B) = 0,6+0,3-0,2-0,2=0,5$.

\newpage